### 
GET http://localhost:3000/api/medicos


### 
GET http://localhost:3000/api/medicos/667c173c6ff7e0656ef5b8fc

### 
POST http://localhost:3000/api/medicos
Content-Type: application/json

{
    "apellido": "ape",
    "nombre": "nom",
    "dni": "123",
    "matricula": "333",
    "especialidad": "sas"
}

### 
PUT http://localhost:3000/api/medicos/667c173c6ff7e0656ef5b8fc
Content-Type: application/json

{
    "apellido": "sas",
    "nombre": "sos",
    "dni": "1234",
    "especialidad": "sas"    
}

### 
PATCH http://localhost:3000/api/medicos/667c173c6ff7e0656ef5b8fc
Content-Type: application/json

{
    "apellido": "sasos",
    "nombre": "das",
    "dni": "1234",
    "especialidad": "nashe"  
}

### 
DELETE http://localhost:3000/api/medicos/667c173c6ff7e0656ef5b8fc